# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Wasserman5/Desktop/XUP/ip/wiring_IP/wiring_IP.cache/wt [current_project]
set_property parent.project_path C:/Users/Wasserman5/Desktop/XUP/ip/wiring_IP/wiring_IP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:microzed_7010:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/Wasserman5/Desktop/XUP/ip/wiring_IP/wiring_IP.srcs/sources_1/imports/CBC/wiring.v
synth_design -top wiring -part xc7z010clg400-1 -flatten_hierarchy full
write_checkpoint -noxdef wiring.dcp
catch { report_utilization -file wiring_utilization_synth.rpt -pb wiring_utilization_synth.pb }
